# To execute this docker compose file, use `docker compose up --build`

name: wdio

services:
  mocha:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TESTING_URL=${TESTING_URL}

  cucumber:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TESTING_URL=${TESTING_URL}
    command: npm run test:cucumber
