name: Run Tests

run-name: Running all tests to ensure they run clear before pull

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

  env:
    TESTING_URL: https://uitestingplayground.com

jobs:
  check-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installing packages
        run: npm install

      - name: Mocha Test
        run: npm run test

      - name: Cucumber Test
        run: npm run test:cucumber
